export const comunasChile = [
  // Arica y Parinacota
  'Arica',
  'Camarones',
  'Putre',
  'General Lagos',

  // Tarapacá
  'Iquique',
  'Alto Hospicio',
  'Pozo Almonte',
  'Camiña',
  'Colchane',
  'Huara',
  'Pica',

  // Antofagasta
  'Antofagasta',
  'Mejillones',
  'Sierra Gorda',
  'Taltal',
  'Calama',
  'Ollagüe',
  'San Pedro de Atacama',
  'Tocopilla',
  'María Elena',

  // Atacama
  'Copiapó',
  'Caldera',
  'Tierra Amarilla',
  'Chañaral',
  'Diego de Almagro',
  'Vallenar',
  'Alto del Carmen',
  'Freirina',
  'Huasco',

  // Coquimbo
  'La Serena',
  'Coquimbo',
  'Andacollo',
  'La Higuera',
  'Paihuano',
  'Vicuña',
  'Illapel',
  'Canela',
  'Los Vilos',
  'Salamanca',
  'Ovalle',
  'Combarbalá',
  'Monte Patria',
  'Punitaqui',
  'Río Hurtado',

  // Valparaíso
  'Valparaíso',
  'Viña del Mar',
  'Concón',
  'Quilpué',
  'Villa Alemana',
  'Casablanca',
  'Quintero',
  'Puchuncaví',
  'San Antonio',
  'Cartagena',
  'El Quisco',
  'El Tabo',
  'Algarrobo',
  'Santo Domingo',
  'Los Andes',
  'San Esteban',
  'Calle Larga',
  'Rinconada',
  'San Felipe',
  'Putaendo',
  'Santa María',
  'Panquehue',
  'Catemu',
  'Llaillay',
  'Nogales',
  'La Calera',
  'Hijuelas',
  'La Cruz',
  'Quillota',
  'Limache',
  'Olmué',
  'Petorca',
  'Cabildo',
  'La Ligua',
  'Papudo',
  'Zapallar',

  // Metropolitana
  'Santiago',
  'Cerrillos',
  'Cerro Navia',
  'Conchalí',
  'El Bosque',
  'Estación Central',
  'Huechuraba',
  'Independencia',
  'La Cisterna',
  'La Florida',
  'La Granja',
  'La Pintana',
  'La Reina',
  'Las Condes',
  'Lo Barnechea',
  'Lo Espejo',
  'Lo Prado',
  'Macul',
  'Maipú',
  'Ñuñoa',
  'Pedro Aguirre Cerda',
  'Peñalolén',
  'Providencia',
  'Pudahuel',
  'Quilicura',
  'Quinta Normal',
  'Recoleta',
  'Renca',
  'San Joaquín',
  'San Miguel',
  'San Ramón',
  'Vitacura',
  'Puente Alto',
  'Pirque',
  'San José de Maipo',
  'Buin',
  'Calera de Tango',
  'Paine',
  'San Bernardo',
  'Melipilla',
  'Alhué',
  'Curacaví',
  'María Pinto',
  'San Pedro',
  'Talagante',
  'El Monte',
  'Isla de Maipo',
  'Padre Hurtado',
  'Peñaflor',

  // O'Higgins
  'Rancagua',
  'Machalí',
  'Graneros',
  'Mostazal',
  'Codegua',
  'Doñihue',
  'Coltauco',
  'Coinco',
  'Olivar',
  'Requínoa',
  'Malloa',
  'San Vicente',
  'Peumo',
  'Pichidegua',
  'Las Cabras',
  'San Fernando',
  'Chimbarongo',
  'Nancagua',
  'Placilla',
  'Palmilla',
  'Peralillo',
  'Pumanque',
  'Santa Cruz',
  'Lolol',
  'Pichilemu',
  'Marchigüe',
  'Litueche',
  'La Estrella',
  'Navidad',

    // Maule
  'Talca',
  'Constitución',
  'Curepto',
  'Empedrado',
  'Maule',
  'Pelarco',
  'Pencahue',
  'Río Claro',
  'San Clemente',
  'San Rafael',
  'Curicó',
  'Hualañé',
  'Licantén',
  'Molina',
  'Rauco',
  'Romeral',
  'Sagrada Familia',
  'Teno',
  'Vichuquén',
  'Linares',
  'Colbún',
  'Longaví',
  'Parral',
  'Retiro',
  'San Javier',
  'Villa Alegre',
  'Yerbas Buenas',
  'Cauquenes',
  'Chanco',
  'Pelluhue',

  // Ñuble
  'Chillán',
  'Bulnes',
  'Cobquecura',
  'Coelemu',
  'Coihueco',
  'El Carmen',
  'Ninhue',
  'Ñiquén',
  'Pemuco',
  'Pinto',
  'Portezuelo',
  'Quillón',
  'Quirihue',
  'Ránquil',
  'San Carlos',
  'San Fabián',
  'San Ignacio',
  'San Nicolás',
  'Trehuaco',
  'Yungay',
  'Chillán Viejo',

  // Biobío
  'Concepción',
  'Coronel',
  'Chiguayante',
  'Florida',
  'Hualqui',
  'Lota',
  'Penco',
  'San Pedro de la Paz',
  'Santa Juana',
  'Talcahuano',
  'Tomé',
  'Hualpén',
  'Los Ángeles',
  'Antuco',
  'Cabrero',
  'Laja',
  'Mulchén',
  'Nacimiento',
  'Negrete',
  'Quilaco',
  'Quilleco',
  'San Rosendo',
  'Santa Bárbara',
  'Tucapel',
  'Yumbel',
  'Alto Biobío',
  'Lebu',
  'Arauco',
  'Cañete',
  'Contulmo',
  'Curanilahue',
  'Los Álamos',
  'Tirúa',

  // Araucanía
  'Temuco',
  'Carahue',
  'Cunco',
  'Curarrehue',
  'Freire',
  'Galvarino',
  'Gorbea',
  'Lautaro',
  'Loncoche',
  'Melipeuco',
  'Nueva Imperial',
  'Padre Las Casas',
  'Perquenco',
  'Pitrufquén',
  'Pucón',
  'Saavedra',
  'Teodoro Schmidt',
  'Toltén',
  'Vilcún',
  'Villarrica',
  'Cholchol',
  'Angol',
  'Collipulli',
  'Curacautín',
  'Ercilla',
  'Lonquimay',
  'Los Sauces',
  'Lumaco',
  'Purén',
  'Renaico',
  'Traiguén',
  'Victoria',

    // Los Ríos
  'Valdivia',
  'Corral',
  'Lanco',
  'Los Lagos',
  'Máfil',
  'Mariquina',
  'Paillaco',
  'Panguipulli',
  'La Unión',
  'Futrono',
  'Lago Ranco',
  'Río Bueno',

  // Los Lagos
  'Puerto Montt',
  'Calbuco',
  'Cochamó',
  'Fresia',
  'Frutillar',
  'Los Muermos',
  'Llanquihue',
  'Maullín',
  'Puerto Varas',
  'Castro',
  'Ancud',
  'Chonchi',
  'Curaco de Vélez',
  'Dalcahue',
  'Puqueldón',
  'Queilén',
  'Quellón',
  'Quemchi',
  'Quinchao',
  'Osorno',
  'Puerto Octay',
  'Purranque',
  'Puyehue',
  'Río Negro',
  'San Juan de la Costa',
  'San Pablo',
  'Chaitén',
  'Futaleufú',
  'Hualaihué',
  'Palena',

  // Aysén
  'Coyhaique',
  'Lago Verde',
  'Aysén',
  'Cisnes',
  'Guaitecas',
  'Cochrane',
  'O’Higgins',
  'Tortel',
  'Chile Chico',
  'Río Ibáñez',

  // Magallanes y Antártica Chilena
  'Punta Arenas',
  'Laguna Blanca',
  'Río Verde',
  'San Gregorio',
  'Cabo de Hornos',
  'Antártica',
  'Porvenir',
  'Primavera',
  'Timaukel',
  'Natales',
  'Torres del Paine',
];